baseURL: "https://hugo.promethean.systems/"
title: "Promethean Systems v1"
theme: "ananke"
languageCode: "en-us"
defaultContentLanguage: "en"
copyright: "Copyright (C) Promethean Systems, 2025"

params:
  description: "Corporate site"
  contact:
    email: info@promethean.systems
    phone: +31 6 25030662
  subtitle: Resistance is futile!
  color_theme: "auto" # dark/light/auto
  favicon: "/images/favicon.png"
  socialImage: "/images/social.png"
  featured_image: /images/default-featured-image.jpg
  enableRobotsTXT: true
  enableGitInfo: true

build:
  writeStats: true
  useResourceCacheWhen: fallback
  cachebusters:
    - source: assets/.*
      target: assets/.*

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: "github"
    noClasses: false

outputs:
  home: ["HTML", "RSS", "JSON"]

security:
  funcs:
    getenv: "^HUGO_"

privacy:
  disqus:
    disable: false
  googleAnalytics:
    disable: false
    respectDoNotTrack: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  x:
    disable: false
    enableDNT: false
    simple: false
  youTube:
    disable: false
    privacyEnhanced: false

#module:
#  imports:
#  - path: github.com/theNewDynamic/gohugo-theme-ananke
