main:
  - identifier: "home"
    name: "Home"
    url: "/"
    weight: 1
  - identifier: "products"
    name: "Products"
    url: "/products/"
    weight: 2
  - identifier: "about"
    name: "About Us"
    url: "/about/"
    weight: 3
  - identifier: "contact"
    name: "Contact Us"
    url: "/contact/"
    weight: 4

footer:
  - identifier: "terms"
    name: "Terms"
    url: "/terms"
    weight: 10
  - identifier: "privacy"
    name: "Privacy"
    url: "/privacy"
    weight: 20