header:
  - identifier: "home"
    name: "Home"
    url: "/"
    weight: 1
  - identifier: "about"
    name: "About Us"
    url: "/about/"
    weight: 2
  - identifier: "products"
    name: "Products"
    url: "/products/"
    weight: 3
  - identifier: "contact"
    name: "Contact"
    url: "/contact/"
    weight: 4
